# Generated by Django 5.0.6 on 2024-05-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('Daily_price', models.CharField(max_length=20)),
                ('Weekly_price', models.CharField(max_length=20)),
                ('Monthly_price', models.CharField(max_length=20)),
                ('MarketValue', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.image')),
            ],
        ),
    ]
