# Generated by Django 5.0.6 on 2024-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Daily_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='Monthly_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='Weekly_price',
            field=models.IntegerField(),
        ),
    ]
