# Generated by Django 5.0.6 on 2025-07-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('s', 'successful')], default='s', max_length=1, null=True),
        ),
    ]
