# Generated by Django 5.0.6 on 2025-07-17 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_alter_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='Daily_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MarketValue',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Monthly_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Weekly_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='period',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_rental_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='min_rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='item',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tools', 'Tools & Equipment'), ('sports', 'Sports & Outdoor'), ('home', 'Home & Garden'), ('automotive', 'Automotive'), ('music', 'Music & Events'), ('photography', 'Photography'), ('fitness', 'Fitness'), ('books', 'Books & Media'), ('clothing', 'Clothing & Accessories'), ('toys', 'Toys & Games'), ('furniture', 'Furniture')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='camera_item_categor_02a27d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price', 'is_active'], name='camera_item_price_956d26_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['location', 'is_active'], name='camera_item_locatio_a23863_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['rating', 'is_active'], name='camera_item_rating_d6f350_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'is_active'], name='camera_item_created_a793e1_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Items/'),
        ),
    ]
