# Generated by Django 5.0.6 on 2025-07-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_alter_item_options_remove_item_daily_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='camera.image'),
        ),
    ]
