# Generated by Django 5.0.6 on 2025-07-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='MarketValue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
