# Generated by Django 5.0.6 on 2024-07-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='earnings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
