# Generated by Django 5.0.6 on 2024-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs'),
        ),
    ]
