# Generated by Django 5.0.6 on 2024-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
